# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js and Python CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies and build
        run: |
          cd server
          npm install
          cd ..
          cd client
          npm install
          npm run build

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r client/src/api/crystal_ball/requirements.txt

      - name: Install Gunicorn
        run: pip install gunicorn

      - name: Run Flask API with Gunicorn
        working-directory: client/src/api/crystal_ball
        run: gunicorn -b 0.0.0.0:5000 api:app
